version: '3.3'

services:
  database:
    image:
      postgres
    container_name: database
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty009
      - POSTGRES_DB=adboard_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      -
  application:
    image:
      application-image
    container_name: application_1
    networks:
      - cloud
    ports:
      - 80:8080
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=qwerty009"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/adboard_db"


volumes:
  postgres_volume:
    external: true

networks:
  cloud:
    external: true
