GET localhost/api/advert

###

GET localhost/api/advert?id=1

###

POST localhost/api/user
Content-Type: application/json

{
  "firstName": "Ilya",
  "lastName": "Ivlev",
  "email": "fdakfjadkfjalf@mail.ru",
  "password": "123123123",
  "phoneNumber": "+78005553535"
}